input_dir: D:/ITU/phd/Data Mining/project/EB-NeRD/dataset
output_dir: D:/ITU/phd/Data Mining/project/EB-NeRD/recsys-challenge-2024-1st-place-master/kami/output
exp_dir: D:/ITU/phd/Data Mining/project/EB-NeRD/recsys-challenge-2024-1st-place-master/kami/output/experiments
features_dir: D:/ITU/phd/Data Mining/project/EB-NeRD/recsys-challenge-2024-1st-place-master/kami/output/features
preprocess_dir: D:/ITU/phd/Data Mining/project/EB-NeRD/recsys-challenge-2024-1st-place-master/kami/output/preprocess
candidate_dir: D:/ITU/phd/Data Mining/project/EB-NeRD/recsys-challenge-2024-1st-place-master/kami/output/preprocess/make_candidate

gcs_bucket: gs://recsys2024/murakami